### ISSUE TITLE
Urlbar freaks out when opening tabs fast

### ISSUE THREAD

**Issue by gurgunday** [cliqz/user-agent-ios#735] opened 2020-01-31 11:54 UTC
## Expected Behavior
While loading a website users should be able to start opening a new tab

## Actual Behavior
While loading a website, if you open a new tab urlbar freaks out and disappears.

## Steps to Reproduce the Problem

  1. Write something on urlbar and click on a website 
  2. Open a new tab real fast
  3. Without waiting start typing something 

[Updated Example](https://gurgunday-drive.mycozy.cloud/public?sharecode=DXQFXH7OtFbE)

## Specifications

  - Version: latest
  - iOS Device: iphone 8

**Comment by chrmod** [comment] 2020-02-06 13:57
Hi @gurgunday thank you for this report. We've linked it to couple other problems with "Pull to reload" functionality and will provide the fix in upcoming update (around Feb 18th). Your help is much appriciated!

**Comment by chrmod** [comment] 2020-02-06 13:57
should be fixed as a part of https://github.com/cliqz/user-agent-ios/issues/728

**Comment by shahenAnt** [comment] 2020-02-10 10:24
This behavior is existing in App Store version but I couldn't reproduce it in current development version. Seems it is fixed now. I am going to close issue.

**Closed** 2020-02-10 10:25 UTC
Labels: Type/Bug

**Comment by chrmod** [comment] 2020-02-10 10:46
@gurgunday If you are interested we can provide you a TestFlight access so you can try yourself the latest build. Just let us know. 
Once again, thank you for reporting the issue!

**Comment by gurgunday** [comment] 2020-02-10 11:10
Great news it got fixed! I use it heavily so it was starting to creep up on me :D Would love to get my hands on a fixed version. I can also report any other bug I come across while browsing the web. However if Feb 18 is still the ETA for the update, I can also wait a few more days...

**Comment by chrmod** [comment] 2020-02-10 11:49
@gurgunday here is the "Nighly" build of the Cliqz Browser, note it may be a little unstable (yet I use as my daily driver). Please don't spread it too much https://testflight.apple.com/join/7C2wm5oL ;-)

**Comment by gurgunday** [comment] 2020-02-10 11:53
Thanks a lot. I will definitely keep this to myself. I will just report the bugs I encounter...
